### ISSUE TITLE
Is 4.0.0 a breaking change

### ISSUE THREAD

**Issue by RobSmyth** [loresoft/Injectio#175]
Is release 4.0.0 a breaking change from 3.x.x? If so ... what are they?

**Comment by RobSmyth** [comment]
Thanks, so unless you say otherwise I'm assuming the project is not using Semmantic versioning and 5.0.0 also does not having breaking changes.  :-)

**Comment by pwelter34** [comment]
There is a slight change to how registration is source generated.  It shouldn't effect the end usage, but I did a full version just in case.  I've done a ton of testing to make sure there wasn't thing breaking, but might have missed something
